# Generated by Django 3.2.9 on 2022-03-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WoodBuildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namename', models.CharField(max_length=20)),
                ('healf', models.IntegerField()),
                ('avatar', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
