# Generated by Django 3.2.9 on 2022-03-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namename', models.CharField(max_length=30)),
                ('healf', models.IntegerField()),
                ('avatar', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='woodbuildings',
            name='namename',
            field=models.CharField(max_length=30),
        ),
    ]
